service: gpt-rss-emailer
org: eiretech
app: gpt-rss-emailer

provider:
    name: aws
    runtime: nodejs18.x
    region: eu-west-1
    stage: ${opt:stage}
    tags:
        environment: ${opt:stage}
        serverless: true
    deploymentBucket:
        name: eire-tech-serverless-deployment-${opt:stage}

functions:
    daily-blast:
        name: daily-blast
        handler: index.handler
        events:
            - schedule:
                  rate: cron(0 9 ? * * *)
                  enabled: true
        timeout: 900
        environment:
            CHAT_GPT_API_KEY: ${ssm:/rss/chat-gpt-api-key}
            GMAIL_EMAIL: ${ssm:/rss/email}
            GMAIL_PASSWORD: ${ssm:/rss/password}

plugins:
    - serverless-prune-plugin

custom:
    prune:
        automatic: true
        number: 1
